build for raspberry 4

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -19,31 +19,31 @@ steps:
     - id: 'clone repository'
       name: gcr.io/cloud-builders/git
       args: ['clone', '${_URL}.git']
-    - id: 'provision infrastructure'
-      name: 'gcr.io/cloud-builders/gcloud'
-      entrypoint: 'bash'
-      args:
-      - '-c'
-      - |
-        echo "Saving eventual failures log to: ${_FAILURE_FILE_PATH}"
+    # - id: 'provision infrastructure'
+    #   name: 'gcr.io/cloud-builders/gcloud'
+    #   entrypoint: 'bash'
+    #   args:
+    #   - '-c'
+    #   - |
+    #     echo "Saving eventual failures log to: ${_FAILURE_FILE_PATH}"
 
-        scripts/submit-cloud-build.sh \
-          --cloud-build-substitutions "BRANCH_NAME=$BRANCH_NAME" \
-          --commit-sha "$COMMIT_SHA" \
-          --destination-directory-path "provisioning/terraform" \
-          --failure-file-path "${_FAILURE_FILE_PATH}" \
-          --git-repository-path "home-lab"
+    #     scripts/submit-cloud-build.sh \
+    #       --cloud-build-substitutions "BRANCH_NAME=$BRANCH_NAME" \
+    #       --commit-sha "$COMMIT_SHA" \
+    #       --destination-directory-path "provisioning/terraform" \
+    #       --failure-file-path "${_FAILURE_FILE_PATH}" \
+    #       --git-repository-path "home-lab"
 
-        # Check if there is any failure.
-        if [ -s "${_FAILURE_FILE_PATH}" ]; then
-            echo
-            echo "Some builds failed:"
-            cat "${_FAILURE_FILE_PATH}"
-            echo "Exiting."
-            exit 1
-        else
-            echo "Build succeeded."
-        fi
+    #     # Check if there is any failure.
+    #     if [ -s "${_FAILURE_FILE_PATH}" ]; then
+    #         echo
+    #         echo "Some builds failed:"
+    #         cat "${_FAILURE_FILE_PATH}"
+    #         echo "Exiting."
+    #         exit 1
+    #     else
+    #         echo "Build succeeded."
+    #     fi
     - id: 'start other build jobs'
       name: 'gcr.io/cloud-builders/gcloud'
       entrypoint: 'bash'
@@ -52,13 +52,13 @@ steps:
       - |
         echo "Saving eventual failures log to: ${_FAILURE_FILE_PATH}"
 
-        scripts/submit-cloud-build.sh \
-          --cloud-build-substitutions "COMMIT_SHA=$COMMIT_SHA,BRANCH_NAME=$BRANCH_NAME,TAG_NAME=$TAG_NAME" \
-          --commit-sha "$COMMIT_SHA" \
-          --destination-directory-path "provisioning/esp32/smart_desk" \
-          --failure-file-path "${_FAILURE_FILE_PATH}" \
-          --git-repository-path "home-lab" \
-          &
+        # scripts/submit-cloud-build.sh \
+        #   --cloud-build-substitutions "COMMIT_SHA=$COMMIT_SHA,BRANCH_NAME=$BRANCH_NAME,TAG_NAME=$TAG_NAME" \
+        #   --commit-sha "$COMMIT_SHA" \
+        #   --destination-directory-path "provisioning/esp32/smart_desk" \
+        #   --failure-file-path "${_FAILURE_FILE_PATH}" \
+        #   --git-repository-path "home-lab" \
+        #   &
 
         scripts/submit-cloud-build.sh \
           --cloud-build-substitutions "_DOCKER_IMAGE_ID=arm-image-builder,_DOCKER_IMAGE_TAG=$SHORT_SHA" \
@@ -68,17 +68,25 @@ steps:
           --git-repository-path "home-lab" \
           &
 
+        # scripts/submit-cloud-build.sh \
+        #   --cloud-build-substitutions "COMMIT_SHA=$COMMIT_SHA,BRANCH_NAME=$BRANCH_NAME" \
+        #   --commit-sha "$COMMIT_SHA" \
+        #   --destination-directory-path "provisioning/arm/beaglebone-black/rootfs" \
+        #   --failure-file-path "${_FAILURE_FILE_PATH}" \
+        #   --git-repository-path "home-lab" \
+        #   &
+
+        # scripts/submit-cloud-build.sh \
+        #   --commit-sha "$COMMIT_SHA" \
+        #   --destination-directory-path "provisioning/arm/beaglebone-black/image" \
+        #   --failure-file-path "${_FAILURE_FILE_PATH}" \
+        #   --git-repository-path "home-lab" \
+        #   &
+
         scripts/submit-cloud-build.sh \
           --cloud-build-substitutions "COMMIT_SHA=$COMMIT_SHA,BRANCH_NAME=$BRANCH_NAME" \
           --commit-sha "$COMMIT_SHA" \
-          --destination-directory-path "provisioning/arm/beaglebone-black/rootfs" \
-          --failure-file-path "${_FAILURE_FILE_PATH}" \
-          --git-repository-path "home-lab" \
-          &
-
-        scripts/submit-cloud-build.sh \
-          --commit-sha "$COMMIT_SHA" \
-          --destination-directory-path "provisioning/arm/beaglebone-black/image" \
+          --destination-directory-path "provisioning/arm/raspberry-pi" \
           --failure-file-path "${_FAILURE_FILE_PATH}" \
           --git-repository-path "home-lab" \
           &
